__all__ = ["PROTON_BRIDGE_PASSWORD", "PROTON_EMAIL", "SLACK_WEBHOOK_URL"]

import os


PROTON_BRIDGE_PASSWORD = os.getenv("PROTON_BRIDGE_PASSWORD", "")
PROTON_EMAIL = os.getenv("PROTON_EMAIL", "")
SLACK_WEBHOOK_URL = os.getenv("SLACK_WEBHOOK_URL", "")
